Search.appendIndex(
    [
                {
            "fqsen": "\\BarController",
            "name": "BarController",
            "summary": "",
            "url": "classes/BarController.html"
        },                {
            "fqsen": "\\BarController\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/BarController.html#method_list"
        },                {
            "fqsen": "\\BarController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/BarController.html#method_edit"
        },                {
            "fqsen": "\\BarController\u003A\u003Aalta\u0028\u0029",
            "name": "alta",
            "summary": "",
            "url": "classes/BarController.html#method_alta"
        },                {
            "fqsen": "\\BarController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/BarController.html#method_update"
        },                {
            "fqsen": "\\BarController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/BarController.html#method_delete"
        },                {
            "fqsen": "\\BarController\u003A\u003AjsonAll\u0028\u0029",
            "name": "jsonAll",
            "summary": "",
            "url": "classes/BarController.html#method_jsonAll"
        },                {
            "fqsen": "\\BarController\u003A\u003Ajson\u0028\u0029",
            "name": "json",
            "summary": "",
            "url": "classes/BarController.html#method_json"
        },                {
            "fqsen": "\\BarController\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "",
            "url": "classes/BarController.html#method_total"
        },                {
            "fqsen": "\\BarController\u003A\u003AuploadPic\u0028\u0029",
            "name": "uploadPic",
            "summary": "",
            "url": "classes/BarController.html#method_uploadPic"
        },                {
            "fqsen": "\\BarController\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/BarController.html#method_new"
        },                {
            "fqsen": "\\BarController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/BarController.html#method_index"
        },                {
            "fqsen": "\\BarController\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "",
            "url": "classes/BarController.html#method_search"
        },                {
            "fqsen": "\\BarController\u003A\u003AsearchQuery\u0028\u0029",
            "name": "searchQuery",
            "summary": "",
            "url": "classes/BarController.html#method_searchQuery"
        },                {
            "fqsen": "\\BarController\u003A\u003AsearchTotal\u0028\u0029",
            "name": "searchTotal",
            "summary": "",
            "url": "classes/BarController.html#method_searchTotal"
        },                {
            "fqsen": "\\BarController\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/BarController.html#method_map"
        },                {
            "fqsen": "\\BarController\u003A\u003AcompleteJson\u0028\u0029",
            "name": "completeJson",
            "summary": "",
            "url": "classes/BarController.html#method_completeJson"
        },                {
            "fqsen": "\\BarController\u003A\u003Aimages\u0028\u0029",
            "name": "images",
            "summary": "",
            "url": "classes/BarController.html#method_images"
        },                {
            "fqsen": "\\BarController\u003A\u003AAMOUNT_OF_RESULTS_PER_PAGE",
            "name": "AMOUNT_OF_RESULTS_PER_PAGE",
            "summary": "",
            "url": "classes/BarController.html#constant_AMOUNT_OF_RESULTS_PER_PAGE"
        },                {
            "fqsen": "\\GeneralController",
            "name": "GeneralController",
            "summary": "",
            "url": "classes/GeneralController.html"
        },                {
            "fqsen": "\\GeneralController\u003A\u003AtokenSearch\u0028\u0029",
            "name": "tokenSearch",
            "summary": "",
            "url": "classes/GeneralController.html#method_tokenSearch"
        },                {
            "fqsen": "\\GeneralController\u003A\u003AbestPinchosAndReviews\u0028\u0029",
            "name": "bestPinchosAndReviews",
            "summary": "",
            "url": "classes/GeneralController.html#method_bestPinchosAndReviews"
        },                {
            "fqsen": "\\PinchoController",
            "name": "PinchoController",
            "summary": "",
            "url": "classes/PinchoController.html"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/PinchoController.html#method_index"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/PinchoController.html#method_list"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/PinchoController.html#method_new"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/PinchoController.html#method_edit"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Aalta\u0028\u0029",
            "name": "alta",
            "summary": "",
            "url": "classes/PinchoController.html#method_alta"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/PinchoController.html#method_update"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/PinchoController.html#method_delete"
        },                {
            "fqsen": "\\PinchoController\u003A\u003AjsonAll\u0028\u0029",
            "name": "jsonAll",
            "summary": "",
            "url": "classes/PinchoController.html#method_jsonAll"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Ajson\u0028\u0029",
            "name": "json",
            "summary": "",
            "url": "classes/PinchoController.html#method_json"
        },                {
            "fqsen": "\\PinchoController\u003A\u003AuploadPic\u0028\u0029",
            "name": "uploadPic",
            "summary": "",
            "url": "classes/PinchoController.html#method_uploadPic"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "",
            "url": "classes/PinchoController.html#method_total"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "",
            "url": "classes/PinchoController.html#method_search"
        },                {
            "fqsen": "\\PinchoController\u003A\u003AsearchQuery\u0028\u0029",
            "name": "searchQuery",
            "summary": "",
            "url": "classes/PinchoController.html#method_searchQuery"
        },                {
            "fqsen": "\\PinchoController\u003A\u003AsearchTotal\u0028\u0029",
            "name": "searchTotal",
            "summary": "",
            "url": "classes/PinchoController.html#method_searchTotal"
        },                {
            "fqsen": "\\PinchoController\u003A\u003AcompleteJson\u0028\u0029",
            "name": "completeJson",
            "summary": "",
            "url": "classes/PinchoController.html#method_completeJson"
        },                {
            "fqsen": "\\PinchoController\u003A\u003Aimages\u0028\u0029",
            "name": "images",
            "summary": "",
            "url": "classes/PinchoController.html#method_images"
        },                {
            "fqsen": "\\PinchoController\u003A\u003AAMOUNT_OF_RESULTS_PER_PAGE",
            "name": "AMOUNT_OF_RESULTS_PER_PAGE",
            "summary": "",
            "url": "classes/PinchoController.html#constant_AMOUNT_OF_RESULTS_PER_PAGE"
        },                {
            "fqsen": "\\ReviewController",
            "name": "ReviewController",
            "summary": "",
            "url": "classes/ReviewController.html"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/ReviewController.html#method_list"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/ReviewController.html#method_edit"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Aalta\u0028\u0029",
            "name": "alta",
            "summary": "",
            "url": "classes/ReviewController.html#method_alta"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/ReviewController.html#method_update"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/ReviewController.html#method_delete"
        },                {
            "fqsen": "\\ReviewController\u003A\u003AjsonAll\u0028\u0029",
            "name": "jsonAll",
            "summary": "",
            "url": "classes/ReviewController.html#method_jsonAll"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Ajson\u0028\u0029",
            "name": "json",
            "summary": "",
            "url": "classes/ReviewController.html#method_json"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "",
            "url": "classes/ReviewController.html#method_total"
        },                {
            "fqsen": "\\ReviewController\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "",
            "url": "classes/ReviewController.html#method_publish"
        },                {
            "fqsen": "\\ReviewController\u003A\u003AAMOUNT_OF_RESULTS_PER_PAGE",
            "name": "AMOUNT_OF_RESULTS_PER_PAGE",
            "summary": "",
            "url": "classes/ReviewController.html#constant_AMOUNT_OF_RESULTS_PER_PAGE"
        },                {
            "fqsen": "\\UserController",
            "name": "UserController",
            "summary": "",
            "url": "classes/UserController.html"
        },                {
            "fqsen": "\\UserController\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/UserController.html#method_list"
        },                {
            "fqsen": "\\UserController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/UserController.html#method_edit"
        },                {
            "fqsen": "\\UserController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/UserController.html#method_login"
        },                {
            "fqsen": "\\UserController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/UserController.html#method_register"
        },                {
            "fqsen": "\\UserController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/UserController.html#method_logout"
        },                {
            "fqsen": "\\UserController\u003A\u003AredirectSession\u0028\u0029",
            "name": "redirectSession",
            "summary": "",
            "url": "classes/UserController.html#method_redirectSession"
        },                {
            "fqsen": "\\UserController\u003A\u003Aalta\u0028\u0029",
            "name": "alta",
            "summary": "",
            "url": "classes/UserController.html#method_alta"
        },                {
            "fqsen": "\\UserController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/UserController.html#method_update"
        },                {
            "fqsen": "\\UserController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/UserController.html#method_delete"
        },                {
            "fqsen": "\\UserController\u003A\u003AjsonAll\u0028\u0029",
            "name": "jsonAll",
            "summary": "",
            "url": "classes/UserController.html#method_jsonAll"
        },                {
            "fqsen": "\\UserController\u003A\u003Ajson\u0028\u0029",
            "name": "json",
            "summary": "",
            "url": "classes/UserController.html#method_json"
        },                {
            "fqsen": "\\UserController\u003A\u003AcompleteDelete\u0028\u0029",
            "name": "completeDelete",
            "summary": "",
            "url": "classes/UserController.html#method_completeDelete"
        },                {
            "fqsen": "\\UserController\u003A\u003AupdateReview\u0028\u0029",
            "name": "updateReview",
            "summary": "",
            "url": "classes/UserController.html#method_updateReview"
        },                {
            "fqsen": "\\UserController\u003A\u003AdeleteReview\u0028\u0029",
            "name": "deleteReview",
            "summary": "",
            "url": "classes/UserController.html#method_deleteReview"
        },                {
            "fqsen": "\\UserController\u003A\u003AdeleteLikes\u0028\u0029",
            "name": "deleteLikes",
            "summary": "",
            "url": "classes/UserController.html#method_deleteLikes"
        },                {
            "fqsen": "\\UserController\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "",
            "url": "classes/UserController.html#method_total"
        },                {
            "fqsen": "\\UserController\u003A\u003Aprofile\u0028\u0029",
            "name": "profile",
            "summary": "",
            "url": "classes/UserController.html#method_profile"
        },                {
            "fqsen": "\\UserController\u003A\u003Aupdate_profile\u0028\u0029",
            "name": "update_profile",
            "summary": "",
            "url": "classes/UserController.html#method_update_profile"
        },                {
            "fqsen": "\\UserController\u003A\u003AvoteReview\u0028\u0029",
            "name": "voteReview",
            "summary": "",
            "url": "classes/UserController.html#method_voteReview"
        },                {
            "fqsen": "\\UserController\u003A\u003AremoveVote\u0028\u0029",
            "name": "removeVote",
            "summary": "",
            "url": "classes/UserController.html#method_removeVote"
        },                {
            "fqsen": "\\UserController\u003A\u003AdeleteMyReview\u0028\u0029",
            "name": "deleteMyReview",
            "summary": "",
            "url": "classes/UserController.html#method_deleteMyReview"
        },                {
            "fqsen": "\\UserController\u003A\u003AAMOUNT_OF_RESULTS_PER_PAGE",
            "name": "AMOUNT_OF_RESULTS_PER_PAGE",
            "summary": "",
            "url": "classes/UserController.html#constant_AMOUNT_OF_RESULTS_PER_PAGE"
        },                {
            "fqsen": "\\DB_USER",
            "name": "DB_USER",
            "summary": "",
            "url": "namespaces/default.html#constant_DB_USER"
        },                {
            "fqsen": "\\DB_PASS",
            "name": "DB_PASS",
            "summary": "",
            "url": "namespaces/default.html#constant_DB_PASS"
        },                {
            "fqsen": "\\DB_INFO",
            "name": "DB_INFO",
            "summary": "",
            "url": "namespaces/default.html#constant_DB_INFO"
        },                {
            "fqsen": "\\get_db_connection\u0028\u0029",
            "name": "get_db_connection",
            "summary": "Obtains\u0020the\u0020database\u0020connection.",
            "url": "namespaces/default.html#function_get_db_connection"
        },                {
            "fqsen": "\\get_server_index_base_url\u0028\u0029",
            "name": "get_server_index_base_url",
            "summary": "Gets\u0020the\u0020url\u0020for\u0020adding\u0020subdomains",
            "url": "namespaces/default.html#function_get_server_index_base_url"
        },                {
            "fqsen": "\\get_root_url\u0028\u0029",
            "name": "get_root_url",
            "summary": "Gets\u0020the\u0020url\u0020path\u0020where\u0020the\u0020index.php\u0020is\u0020located\u0020at.",
            "url": "namespaces/default.html#function_get_root_url"
        },                {
            "fqsen": "\\check_session\u0028\u0029",
            "name": "check_session",
            "summary": "Checks\u0020the\u0020user\u0020session\u0020for\u0020admin",
            "url": "namespaces/default.html#function_check_session"
        },                {
            "fqsen": "\\add_to_breadcrumbs\u0028\u0029",
            "name": "add_to_breadcrumbs",
            "summary": "Add\u0020another\u0020step\u0020to\u0020the\u0020bread\u0020crumbs",
            "url": "namespaces/default.html#function_add_to_breadcrumbs"
        },                {
            "fqsen": "\\is_admin_for_api\u0028\u0029",
            "name": "is_admin_for_api",
            "summary": "Checks\u0020if\u0020the\u0020request\u0020has\u0020been\u0020made\u0020by\u0020an\u0020admin.\u0020If\u0020not,\u0020returns\u0020401",
            "url": "namespaces/default.html#function_is_admin_for_api"
        },                {
            "fqsen": "\\is_admin\u0028\u0029",
            "name": "is_admin",
            "summary": "Checks\u0020if\u0020a\u0020user\u0020is\u0020an\u0020admin.\u0020\u0028Based\u0020on\u0020PHP\u0020\u0024_SESSION\u0029",
            "url": "namespaces/default.html#function_is_admin"
        },                {
            "fqsen": "\\is_logged\u0028\u0029",
            "name": "is_logged",
            "summary": "Checks\u0020if\u0020the\u0020user\u0020is\u0020logged.",
            "url": "namespaces/default.html#function_is_logged"
        },                {
            "fqsen": "\\get_system_web_root_folder_path\u0028\u0029",
            "name": "get_system_web_root_folder_path",
            "summary": "Gets\u0020the\u0020system\u0020root\u0020path\u0020for\u0020the\u0020current\u0020web,\u0020which\u0020means,\u0020it\u0020returns\u0020the\u0020dirname\u0020of\u0020the\u0020index.php\u0020of\u0020this\u0020mvc.",
            "url": "namespaces/default.html#function_get_system_web_root_folder_path"
        },                {
            "fqsen": "\\AbstractMappedSQLModel",
            "name": "AbstractMappedSQLModel",
            "summary": "Makes\u0020easier\u0020to\u0020convert\u0020SQL\u0020fetch\u0020data\u0020and\u0020stdClass\u0020into\u0020instance\u0020of\u0020a\u0020class\u0020by\u0020just\u0020calling\u0020the\u0020getInstance\u0028\u0029\u0020method.",
            "url": "classes/AbstractMappedSQLModel.html"
        },                {
            "fqsen": "\\AbstractMappedSQLModel\u003A\u003AgetPropertiesMapArray\u0028\u0029",
            "name": "getPropertiesMapArray",
            "summary": "Gets\u0020the\u0020object\u0020properties\u0020relations\u0020with\u0020the\u0020SQL\u0020result\u0020fields",
            "url": "classes/AbstractMappedSQLModel.html#method_getPropertiesMapArray"
        },                {
            "fqsen": "\\AbstractMappedSQLModel\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "Gets\u0020a\u0020new\u0020instance\u0020from\u0020the\u0020fetch\u0020data.",
            "url": "classes/AbstractMappedSQLModel.html#method_getInstance"
        },                {
            "fqsen": "\\Bar",
            "name": "Bar",
            "summary": "Represents\u0020a\u0020Bar",
            "url": "classes/Bar.html"
        },                {
            "fqsen": "\\Bar\u003A\u003AgetPropertiesMapArray\u0028\u0029",
            "name": "getPropertiesMapArray",
            "summary": "Gets\u0020the\u0020object\u0020properties\u0020relations\u0020with\u0020the\u0020SQL\u0020result\u0020fields",
            "url": "classes/Bar.html#method_getPropertiesMapArray"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Bar.html#property_id"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Bar.html#property_name"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024desc",
            "name": "desc",
            "summary": "",
            "url": "classes/Bar.html#property_desc"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024address",
            "name": "address",
            "summary": "",
            "url": "classes/Bar.html#property_address"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024lon",
            "name": "lon",
            "summary": "",
            "url": "classes/Bar.html#property_lon"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024lat",
            "name": "lat",
            "summary": "",
            "url": "classes/Bar.html#property_lat"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024terrace",
            "name": "terrace",
            "summary": "",
            "url": "classes/Bar.html#property_terrace"
        },                {
            "fqsen": "\\Bar\u003A\u003A\u0024rating",
            "name": "rating",
            "summary": "",
            "url": "classes/Bar.html#property_rating"
        },                {
            "fqsen": "\\Pincho",
            "name": "Pincho",
            "summary": "Represents\u0020a\u0020Pincho",
            "url": "classes/Pincho.html"
        },                {
            "fqsen": "\\Pincho\u003A\u003AgetPropertiesMapArray\u0028\u0029",
            "name": "getPropertiesMapArray",
            "summary": "Gets\u0020the\u0020object\u0020properties\u0020relations\u0020with\u0020the\u0020SQL\u0020result\u0020fields",
            "url": "classes/Pincho.html#method_getPropertiesMapArray"
        },                {
            "fqsen": "\\Pincho\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Pincho.html#property_id"
        },                {
            "fqsen": "\\Pincho\u003A\u003A\u0024bar_id",
            "name": "bar_id",
            "summary": "",
            "url": "classes/Pincho.html#property_bar_id"
        },                {
            "fqsen": "\\Pincho\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Pincho.html#property_name"
        },                {
            "fqsen": "\\Pincho\u003A\u003A\u0024desc",
            "name": "desc",
            "summary": "",
            "url": "classes/Pincho.html#property_desc"
        },                {
            "fqsen": "\\Pincho\u003A\u003A\u0024price",
            "name": "price",
            "summary": "",
            "url": "classes/Pincho.html#property_price"
        },                {
            "fqsen": "\\Pincho\u003A\u003A\u0024rating",
            "name": "rating",
            "summary": "",
            "url": "classes/Pincho.html#property_rating"
        },                {
            "fqsen": "\\Pincho\u003A\u003A\u0024bar_name",
            "name": "bar_name",
            "summary": "",
            "url": "classes/Pincho.html#property_bar_name"
        },                {
            "fqsen": "\\Review",
            "name": "Review",
            "summary": "Represents\u0020a\u0020Review",
            "url": "classes/Review.html"
        },                {
            "fqsen": "\\Review\u003A\u003AgetPropertiesMapArray\u0028\u0029",
            "name": "getPropertiesMapArray",
            "summary": "Gets\u0020the\u0020object\u0020properties\u0020relations\u0020with\u0020the\u0020SQL\u0020result\u0020fields",
            "url": "classes/Review.html#method_getPropertiesMapArray"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Review.html#property_id"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024user_id",
            "name": "user_id",
            "summary": "",
            "url": "classes/Review.html#property_user_id"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Review.html#property_title"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024desc",
            "name": "desc",
            "summary": "",
            "url": "classes/Review.html#property_desc"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024presentation",
            "name": "presentation",
            "summary": "",
            "url": "classes/Review.html#property_presentation"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024texture",
            "name": "texture",
            "summary": "",
            "url": "classes/Review.html#property_texture"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024taste",
            "name": "taste",
            "summary": "",
            "url": "classes/Review.html#property_taste"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024pincho_id",
            "name": "pincho_id",
            "summary": "",
            "url": "classes/Review.html#property_pincho_id"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024likes",
            "name": "likes",
            "summary": "",
            "url": "classes/Review.html#property_likes"
        },                {
            "fqsen": "\\Review\u003A\u003A\u0024dislikes",
            "name": "dislikes",
            "summary": "",
            "url": "classes/Review.html#property_dislikes"
        },                {
            "fqsen": "\\User",
            "name": "User",
            "summary": "Represents\u0020a\u0020User",
            "url": "classes/User.html"
        },                {
            "fqsen": "\\User\u003A\u003AgetPropertiesMapArray\u0028\u0029",
            "name": "getPropertiesMapArray",
            "summary": "Gets\u0020the\u0020object\u0020properties\u0020relations\u0020with\u0020the\u0020SQL\u0020result\u0020fields",
            "url": "classes/User.html#method_getPropertiesMapArray"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/User.html#property_id"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024first_name",
            "name": "first_name",
            "summary": "",
            "url": "classes/User.html#property_first_name"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024last_name",
            "name": "last_name",
            "summary": "",
            "url": "classes/User.html#property_last_name"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/User.html#property_email"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/User.html#property_password"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024admin",
            "name": "admin",
            "summary": "",
            "url": "classes/User.html#property_admin"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024created_date",
            "name": "created_date",
            "summary": "",
            "url": "classes/User.html#property_created_date"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024img_path",
            "name": "img_path",
            "summary": "",
            "url": "classes/User.html#property_img_path"
        },                {
            "fqsen": "\\AllergenRepository",
            "name": "AllergenRepository",
            "summary": "Manage\u0020operations\u0020in\u0020the\u0020database\u0020for\u0020entities.",
            "url": "classes/AllergenRepository.html"
        },                {
            "fqsen": "\\AllergenRepository\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Obtains\u0020all\u0020the\u0020allergens\u0020from\u0020the\u0020database.",
            "url": "classes/AllergenRepository.html#method_findAll"
        },                {
            "fqsen": "\\BarRepository",
            "name": "BarRepository",
            "summary": "Manage\u0020operations\u0020in\u0020the\u0020database\u0020for\u0020bar\u0020entities.",
            "url": "classes/BarRepository.html"
        },                {
            "fqsen": "\\BarRepository\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Obtains\u0020a\u0020bar\u0020from\u0020the\u0020database.",
            "url": "classes/BarRepository.html#method_find"
        },                {
            "fqsen": "\\BarRepository\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Obtains\u0020all\u0020the\u0020bars\u0020from\u0020the\u0020database.\u0020Supports\u0020pagination.",
            "url": "classes/BarRepository.html#method_findAll"
        },                {
            "fqsen": "\\BarRepository\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Inserts\u0020a\u0020new\u0020bar\u0020into\u0020the\u0020database",
            "url": "classes/BarRepository.html#method_save"
        },                {
            "fqsen": "\\BarRepository\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020a\u0020bar\u0020from\u0020the\u0020database",
            "url": "classes/BarRepository.html#method_delete"
        },                {
            "fqsen": "\\BarRepository\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020a\u0020bar\u0020from\u0020the\u0020database",
            "url": "classes/BarRepository.html#method_update"
        },                {
            "fqsen": "\\BarRepository\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "Returns\u0020the\u0020total\u0020amount\u0020of\u0020bars\u0020on\u0020the\u0020database.",
            "url": "classes/BarRepository.html#method_total"
        },                {
            "fqsen": "\\BarRepository\u003A\u003AuploadPic\u0028\u0029",
            "name": "uploadPic",
            "summary": "Uploads\u0020a\u0020picture\u0020for\u0020a\u0020bar.",
            "url": "classes/BarRepository.html#method_uploadPic"
        },                {
            "fqsen": "\\BarRepository\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "Returns\u0020the\u0020images\u0020of\u0020a\u0020bar\u0020by\u0020ID.",
            "url": "classes/BarRepository.html#method_getImages"
        },                {
            "fqsen": "\\BarRepository\u003A\u003AgetImagesForArray\u0028\u0029",
            "name": "getImagesForArray",
            "summary": "",
            "url": "classes/BarRepository.html#method_getImagesForArray"
        },                {
            "fqsen": "\\BarRepository\u003A\u003AtreatImages\u0028\u0029",
            "name": "treatImages",
            "summary": "Manages\u0020the\u0020bar\u0020images",
            "url": "classes/BarRepository.html#method_treatImages"
        },                {
            "fqsen": "\\BarRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Advance\u0020search\u0020for\u0020bars.",
            "url": "classes/BarRepository.html#method_search"
        },                {
            "fqsen": "\\BarRepository\u003A\u003AsearchTotal\u0028\u0029",
            "name": "searchTotal",
            "summary": "Gets\u0020the\u0020total\u0020amount\u0020of\u0020results\u0020of\u0020an\u0020advance\u0020search.\u0020Useful\u0020for\u0020pagination.",
            "url": "classes/BarRepository.html#method_searchTotal"
        },                {
            "fqsen": "\\BarRepository\u003A\u003AtokenSearch\u0028\u0029",
            "name": "tokenSearch",
            "summary": "Obtains\u0020the\u0020bars\u0020from\u0020the\u0020database\u0020that\u0020the\u0020name\u0020or\u0020desc\u0020contains\u0020the\u0020specified\u0020string.",
            "url": "classes/BarRepository.html#method_tokenSearch"
        },                {
            "fqsen": "\\IDAO",
            "name": "IDAO",
            "summary": "",
            "url": "classes/IDAO.html"
        },                {
            "fqsen": "\\IDAO\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Searches\u0020the\u0020entity\u0020by\u0020id\u0020from\u0020the\u0020DB",
            "url": "classes/IDAO.html#method_find"
        },                {
            "fqsen": "\\IDAO\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Gets\u0020all\u0020the\u0020data\u0020from\u0020the\u0020table.",
            "url": "classes/IDAO.html#method_findAll"
        },                {
            "fqsen": "\\IDAO\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Saves\/inserts\u0020the\u0020entity\u0020into\u0020the\u0020DB",
            "url": "classes/IDAO.html#method_save"
        },                {
            "fqsen": "\\IDAO\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020an\u0020entity\u0020fields",
            "url": "classes/IDAO.html#method_update"
        },                {
            "fqsen": "\\IDAO\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020an\u0020entity\u0020by\u0020ID",
            "url": "classes/IDAO.html#method_delete"
        },                {
            "fqsen": "\\PinchoRepository",
            "name": "PinchoRepository",
            "summary": "Manage\u0020operations\u0020in\u0020the\u0020database\u0020for\u0020pincho\u0020entities.",
            "url": "classes/PinchoRepository.html"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Obtains\u0020a\u0020pincho\u0020from\u0020the\u0020database.",
            "url": "classes/PinchoRepository.html#method_find"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Obtains\u0020all\u0020the\u0020pinchos\u0020from\u0020the\u0020database.\u0020Supports\u0020pagination.",
            "url": "classes/PinchoRepository.html#method_findAll"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Inserts\u0020a\u0020new\u0020pincho\u0020into\u0020the\u0020database",
            "url": "classes/PinchoRepository.html#method_save"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020a\u0020pincho\u0020from\u0020the\u0020database",
            "url": "classes/PinchoRepository.html#method_delete"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020a\u0020pincho\u0020from\u0020the\u0020database",
            "url": "classes/PinchoRepository.html#method_update"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "Returns\u0020the\u0020total\u0020amount\u0020of\u0020pinchos\u0020on\u0020the\u0020database.",
            "url": "classes/PinchoRepository.html#method_total"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AuploadPic\u0028\u0029",
            "name": "uploadPic",
            "summary": "Uploads\u0020a\u0020picture\u0020for\u0020a\u0020pincho.",
            "url": "classes/PinchoRepository.html#method_uploadPic"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "Returns\u0020the\u0020images\u0020of\u0020a\u0020pincho\u0020by\u0020ID.",
            "url": "classes/PinchoRepository.html#method_getImages"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AtreatImages\u0028\u0029",
            "name": "treatImages",
            "summary": "Manages\u0020the\u0020pincho\u0020images",
            "url": "classes/PinchoRepository.html#method_treatImages"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Advance\u0020search\u0020for\u0020pinchos.",
            "url": "classes/PinchoRepository.html#method_search"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AsearchTotal\u0028\u0029",
            "name": "searchTotal",
            "summary": "Gets\u0020the\u0020total\u0020amount\u0020of\u0020results\u0020of\u0020an\u0020advance\u0020search.\u0020Useful\u0020for\u0020pagination.",
            "url": "classes/PinchoRepository.html#method_searchTotal"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AbyBar\u0028\u0029",
            "name": "byBar",
            "summary": "Obtains\u0020a\u0020bar\u0027s\u0020pinchos.",
            "url": "classes/PinchoRepository.html#method_byBar"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003Alast\u0028\u0029",
            "name": "last",
            "summary": "Get\u0020the\u0020last\u0020pincho\u0027s\u0020by\u0020amount.",
            "url": "classes/PinchoRepository.html#method_last"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AgetAllergens\u0028\u0029",
            "name": "getAllergens",
            "summary": "Gets\u0020allergens\u0020of\u0020a\u0020pincho.",
            "url": "classes/PinchoRepository.html#method_getAllergens"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AsetAllergens\u0028\u0029",
            "name": "setAllergens",
            "summary": "Sets\u0020the\u0020pincho\u0027s\u0020allergens",
            "url": "classes/PinchoRepository.html#method_setAllergens"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AtokenSearch\u0028\u0029",
            "name": "tokenSearch",
            "summary": "Obtains\u0020the\u0020pinchos\u0020from\u0020the\u0020database\u0020that\u0020the\u0020name\u0020or\u0020desc\u0020or\u0020related\u0020reviews\u0020contains\u0020the\u0020specified\u0020string.",
            "url": "classes/PinchoRepository.html#method_tokenSearch"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AfindAllOrderByRating\u0028\u0029",
            "name": "findAllOrderByRating",
            "summary": "Obtains\u0020all\u0020the\u0020pinchos\u0020ordered\u0020by\u0020the\u0020rating.",
            "url": "classes/PinchoRepository.html#method_findAllOrderByRating"
        },                {
            "fqsen": "\\PinchoRepository\u003A\u003AfindAllOrderByUserRating\u0028\u0029",
            "name": "findAllOrderByUserRating",
            "summary": "Gets\u0020all\u0020the\u0020results\u0020from\u0020the\u0020database\u0020ordered\u0020by\u0020the\u0020users\u0020rating",
            "url": "classes/PinchoRepository.html#method_findAllOrderByUserRating"
        },                {
            "fqsen": "\\ReviewRepository",
            "name": "ReviewRepository",
            "summary": "Manage\u0020operations\u0020in\u0020the\u0020database\u0020for\u0020review\u0020entities.",
            "url": "classes/ReviewRepository.html"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Obtains\u0020a\u0020review\u0020from\u0020the\u0020database.",
            "url": "classes/ReviewRepository.html#method_find"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Obtains\u0020all\u0020the\u0020review\u0020from\u0020the\u0020database.\u0020Supports\u0020pagination.",
            "url": "classes/ReviewRepository.html#method_findAll"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Inserts\u0020a\u0020new\u0020review\u0020into\u0020the\u0020database.",
            "url": "classes/ReviewRepository.html#method_save"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020a\u0020review\u0020from\u0020the\u0020database.",
            "url": "classes/ReviewRepository.html#method_delete"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020a\u0020review\u0020from\u0020the\u0020database.",
            "url": "classes/ReviewRepository.html#method_update"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "Returns\u0020the\u0020total\u0020amount\u0020of\u0020reviews\u0020on\u0020the\u0020database.",
            "url": "classes/ReviewRepository.html#method_total"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AbyUser\u0028\u0029",
            "name": "byUser",
            "summary": "Obtains\u0020a\u0020bar\u0027s\u0020reviews.",
            "url": "classes/ReviewRepository.html#method_byUser"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AlikedByUser\u0028\u0029",
            "name": "likedByUser",
            "summary": "Obtains\u0020the\u0020reviews\u0020like\u0020by\u0020an\u0020user.",
            "url": "classes/ReviewRepository.html#method_likedByUser"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AdislikedByUser\u0028\u0029",
            "name": "dislikedByUser",
            "summary": "Obtains\u0020the\u0020reviews\u0020dislike\u0020by\u0020an\u0020user.",
            "url": "classes/ReviewRepository.html#method_dislikedByUser"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003Alast\u0028\u0029",
            "name": "last",
            "summary": "Get\u0020the\u0020last\u0020review\u0027s\u0020by\u0020amount.",
            "url": "classes/ReviewRepository.html#method_last"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AbyPincho\u0028\u0029",
            "name": "byPincho",
            "summary": "Obtains\u0020a\u0020pincho\u0027s\u0020reviews.",
            "url": "classes/ReviewRepository.html#method_byPincho"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AhasBeenVotedByUser\u0028\u0029",
            "name": "hasBeenVotedByUser",
            "summary": "Checks\u0020if\u0020a\u0020review\u0020has\u0020been\u0020voted\u0020by\u0020an\u0020user.",
            "url": "classes/ReviewRepository.html#method_hasBeenVotedByUser"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AdidUserVoteLike\u0028\u0029",
            "name": "didUserVoteLike",
            "summary": "Checks\u0020if\u0020a\u0020user\u0020has\u0020voted\u0020like\u0020on\u0020a\u0020review.",
            "url": "classes/ReviewRepository.html#method_didUserVoteLike"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003AfindAllOrderByRating\u0028\u0029",
            "name": "findAllOrderByRating",
            "summary": "Obtains\u0020all\u0020the\u0020reviews\u0020ordered\u0020by\u0020the\u0020rating.",
            "url": "classes/ReviewRepository.html#method_findAllOrderByRating"
        },                {
            "fqsen": "\\ReviewRepository\u003A\u003ATABLE_NAME",
            "name": "TABLE_NAME",
            "summary": "",
            "url": "classes/ReviewRepository.html#constant_TABLE_NAME"
        },                {
            "fqsen": "\\UserRepository",
            "name": "UserRepository",
            "summary": "Manage\u0020operations\u0020in\u0020the\u0020database\u0020for\u0020user\u0020entities.",
            "url": "classes/UserRepository.html"
        },                {
            "fqsen": "\\UserRepository\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Obtains\u0020an\u0020user\u0020from\u0020the\u0020database\u0020by\u0020email.",
            "url": "classes/UserRepository.html#method_find"
        },                {
            "fqsen": "\\UserRepository\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Obtains\u0020an\u0020user\u0020from\u0020the\u0020database\u0020by\u0020ID.",
            "url": "classes/UserRepository.html#method_findById"
        },                {
            "fqsen": "\\UserRepository\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Obtains\u0020all\u0020the\u0020users\u0020from\u0020the\u0020database.\u0020Supports\u0020pagination.",
            "url": "classes/UserRepository.html#method_findAll"
        },                {
            "fqsen": "\\UserRepository\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Inserts\u0020a\u0020new\u0020pincho\u0020into\u0020the\u0020database.",
            "url": "classes/UserRepository.html#method_save"
        },                {
            "fqsen": "\\UserRepository\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020a\u0020user\u0020from\u0020the\u0020database",
            "url": "classes/UserRepository.html#method_delete"
        },                {
            "fqsen": "\\UserRepository\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020a\u0020user\u0020from\u0020the\u0020database",
            "url": "classes/UserRepository.html#method_update"
        },                {
            "fqsen": "\\UserRepository\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Check\u0020the\u0020login\u0020credentials\u0020of\u0020an\u0020user.",
            "url": "classes/UserRepository.html#method_login"
        },                {
            "fqsen": "\\UserRepository\u003A\u003AremoveLikes\u0028\u0029",
            "name": "removeLikes",
            "summary": "Removes\u0020the\u0020likes\u0020given\u0020by\u0020the\u0020user.",
            "url": "classes/UserRepository.html#method_removeLikes"
        },                {
            "fqsen": "\\UserRepository\u003A\u003AremoveReviews\u0028\u0029",
            "name": "removeReviews",
            "summary": "Removes\u0020the\u0020dislikes\u0020given\u0020by\u0020the\u0020user.",
            "url": "classes/UserRepository.html#method_removeReviews"
        },                {
            "fqsen": "\\UserRepository\u003A\u003AcheckReviewOP\u0028\u0029",
            "name": "checkReviewOP",
            "summary": "Check\u0020if\u0020a\u0020user\u0020is\u0020the\u0020original\u0020poster\u0020of\u0020a\u0020given\u0020review.",
            "url": "classes/UserRepository.html#method_checkReviewOP"
        },                {
            "fqsen": "\\UserRepository\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "Returns\u0020the\u0020total\u0020amount\u0020of\u0020users\u0020on\u0020the\u0020database.",
            "url": "classes/UserRepository.html#method_total"
        },                {
            "fqsen": "\\UserRepository\u003A\u003AvoteReview\u0028\u0029",
            "name": "voteReview",
            "summary": "Vote\u0020a\u0020review.",
            "url": "classes/UserRepository.html#method_voteReview"
        },                {
            "fqsen": "\\UserRepository\u003A\u003AremoveVote\u0028\u0029",
            "name": "removeVote",
            "summary": "Remove\u0020a\u0020vote\u0020from\u0020a\u0020user\u0020to\u0020a\u0020specific\u0020review",
            "url": "classes/UserRepository.html#method_removeVote"
        },                {
            "fqsen": "\\TemplateHelper",
            "name": "TemplateHelper",
            "summary": "General\u0020purpose\u0020class\u0020to\u0020help\u0020with\u0020repetitive\u0020HTML\u0020code\u0020generation.",
            "url": "classes/TemplateHelper.html"
        },                {
            "fqsen": "\\TemplateHelper\u003A\u003AgetStarts\u0028\u0029",
            "name": "getStarts",
            "summary": "Generates\u0020the\u0020stars\u0020for\u0020a\u0020given\u0020rating\u0020and\u0020prints\u0020it.",
            "url": "classes/TemplateHelper.html#method_getStarts"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
